// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Prints the offsets the assembly reaches the shared structures through, as
 * #defines, so that the structures in include/uapi are the only place their
 * layout is written down.  Built and run on the host: every structure here
 * is fixed-width fields at their natural alignment, laid out the same there
 * as on the GPU.
 */
#include <stddef.h>
#include <stdio.h>
#include <linux/knod_blob.h>
#include <linux/knod_mlx5.h>
#include <linux/knod_persistent.h>

#define OFF(name, type, field) \
	printf("#define %-40s %zu\n", name, offsetof(type, field))
#define SIZE(name, type) \
	printf("#define %-40s %zu\n", name, sizeof(type))

#define CTRL(name, field) \
	OFF("KNOD_PERSIST_" name, struct knod_persistent_control, field)
#define GDA(name, field) \
	OFF("KNOD_PERSIST_GDA_" name, struct knod_persistent_gda, field)
#define DESC(name, field) \
	OFF("KNOD_BLOB_DESC_" name, struct knod_blob_map_desc, field)

int main(void)
{
	printf("/* Generated by tools/offsets.c from include/uapi.  Do not edit. */\n");
	printf("#ifndef KNOD_OFFSETS_H\n#define KNOD_OFFSETS_H\n");

	CTRL("STOP", stop);
	CTRL("PAUSE", pause);
	CTRL("PASS_WAKE", pass_wake);
	CTRL("GDA_PARAM", gda_param);
	CTRL("GDA_LDS", gda_lds);
	CTRL("GDA_WAVES", gda_waves);
	CTRL("TX_DB", tx_db);
	CTRL("GDA", gda);

	SIZE("KNOD_PERSIST_GDA_BYTES", struct knod_persistent_gda);
	GDA("RING", ring);
	GDA("RX_DMA", rx_dma);
	GDA("PACKETS", packets);
	GDA("ROUNDS", rounds);
	GDA("RQ_LOG", rq_log);
	GDA("RQ_LOG_STRIDE", rq_log_stride);
	GDA("CQ_LOG", cq_log);
	GDA("FRAG", frag);
	GDA("HEADROOM", headroom);
	GDA("MKEY", mkey_be);
	GDA("LIVE", live);
	GDA("GEN", gen);
	GDA("RX_BASE", rx_base);
	GDA("CI", ci);
	GDA("POSTED_GEN", posted_gen);
	GDA("PAUSE_ACK", pause_ack);
	GDA("SQ", sq);
	GDA("SQN", sqn);
	GDA("SQ_MASK", sq_mask);
	GDA("TX_MKEY", tx_mkey_be);
	GDA("TX_CQ_LOG", tx_cq_log);
	GDA("TX_GEN", tx_gen);
	GDA("TX_PACKETS", tx_packets);
	GDA("TX_FULL", tx_full);
	GDA("SQ_PC", sq_pc);
	GDA("SQ_CC", sq_cc);
	GDA("TX_CI", tx_ci);
	GDA("TX_POSTED_GEN", tx_posted_gen);
	GDA("STAGGER", stagger);
	GDA("STAGGER_MASK", stagger_mask);
	GDA("PASS_RING", pass_ring);
	GDA("PASS_MASK", pass_mask);
	GDA("PASS_PC", pass_pc);
	GDA("PASS_CC", pass_cc);
	GDA("PASS_FLOOR", pass_floor);
	GDA("REGRESS_DBG", regress_dbg);
	GDA("SYNC_DBG", sync_dbg);

	SIZE("KNOD_BLOB_DESC_SIZE", struct knod_blob_map_desc);
	DESC("KEY_SIZE", key_size);
	DESC("VALUE_SIZE", value_size);
	DESC("MAX_ENTRIES", max_entries);
	DESC("ELEM_SIZE", elem_size);
	DESC("BUCKET", bucket_gaddr);
	DESC("ELEMS", elems_gaddr);
	DESC("QUEUE", queue_gaddr);
	DESC("GC_LIST", gc_list_gaddr);
	DESC("GC_COUNT", gc_count_gaddr);
	DESC("PER_INSTANCE", per_instance_size);
	DESC("N_BUCKETS", n_buckets);
	DESC("LOCK_OFFSET", lock_offset);
	DESC("HASHRND", hashrnd);
	DESC("FREE_CUR", free_cur_gaddr);

	OFF("KNOD_MLX5_CQE_BYTE_CNT", struct knod_mlx5_cqe64, byte_cnt);
	OFF("KNOD_MLX5_CQE_WQE_COUNTER", struct knod_mlx5_cqe64, wqe_counter);
	OFF("KNOD_MLX5_CQE_OP_OWN", struct knod_mlx5_cqe64, op_own);
	SIZE("KNOD_MLX5_CQE_BYTES", struct knod_mlx5_cqe64);
	OFF("KNOD_MLX5_CTRL_FM_CE_SE", struct knod_mlx5_wqe_ctrl_seg, fm_ce_se);
	OFF("KNOD_MLX5_SEND_ETH", struct knod_mlx5_send_wqe, eth);
	OFF("KNOD_MLX5_SEND_DATA", struct knod_mlx5_send_wqe, data);
	printf("#define %-40s %zu\n", "KNOD_MLX5_SEND_DS",
	       sizeof(struct knod_mlx5_send_wqe) / 16);

	printf("#endif\n");
	return 0;
}
